clippy/urls.py
from django.urls import path, include

from . import views
from .api.routers import router

urlpatterns = [
    path('', views.ClipListView.as_view(), name='home'),
    path('register/', views.DeviceCreateView.as_view(), name='register'),
    path('api/', include(router.urls)),
]

companion/urls.py
from django.urls import path, include

from .api.routers import router

urlpatterns = [
    path('api/', include(router.urls)),
]

www/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('clippy.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('admin/', admin.site.urls),
]

clippy/models.py
from django.db import models


class Device(models.Model):

    name = models.CharField(max_length=64)


class Clip(models.Model):
    class Meta:
        ordering = ('-timestamp', )

    value = models.TextField()
    timestamp = models.DateTimeField(auto_now=True)

    def found_in_clipboard(self):
        return self.source_set.filter(action='r').count()

    def saved_to_clipboard(self):
        return self.source_set.filter(action='w').count()

    def action(self):
        return self.source_set.first().action

    def device(self):
        return self.source_set.first().device.name


class Source(models.Model):
    class Meta:
        ordering = ('-timestamp', )

    actions = (
        ('r', 'Read from Clipboard'),
        ('w', 'Write to Clipboard'),
    )

    clip = models.ForeignKey(Clip, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now=True)
    device = models.ForeignKey(Device, on_delete=models.CASCADE)
    action = models.CharField(max_length=1, choices=actions)


class Note(models.Model):

    text = models.TextField()
    clip = models.ForeignKey(Clip, on_delete=models.CASCADE)

companion/models.py
from django.db import models


class Clipping(models.Model):
    class Meta:
        managed = False
        db_table = 'ZCLIPPING'
        ordering = ('-pk',)

    id = models.IntegerField(primary_key=True, db_column='z_pk')
    source = models.IntegerField(db_column='zsource')
    contents = models.TextField(db_column='zcontents')
    timestamp = models.DateTimeField(db_column='zdaterecorded')

clippy/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views import generic

from . import utils
from . import models

from logging import getLogger

logger = getLogger(__name__)


class HomeView(generic.TemplateView):
    template_name = 'clippy/home.html'

    def dispatch(self, request, *args, **kwargs):
        if 'device' not in request.session:
            return HttpResponseRedirect(reverse('register'))
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['device'] = self.request.session['device']
        context['device_name'] = self.request.session['device_name']
        return context


class ClipListView(generic.ListView):
    model = models.Clip

    def dispatch(self, request, *args, **kwargs):
        if 'device' not in request.session:
            return HttpResponseRedirect(reverse('register'))
        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self):
        qs = super().get_queryset()
        if 'search' in self.request.GET:
            logger.info('filtering queryset via search.')
            qs = qs.filter(value__icontains=self.request.GET.get('search', ''))
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        device_pk = utils.decode_token(self.request.session['device'])
        context['device'] = self.request.session['device']
        context['device_name'] = self.request.session['device_name']
        most_recent = self.model.objects.filter(source__device__pk=device_pk).first()

        context['search_value'] = self.request.GET.get('search', '')
        if most_recent:
            context['most_recent'] = most_recent.value
        return context


class DeviceCreateView(generic.CreateView):
    model = models.Device
    success_url = reverse_lazy('home')
    fields = '__all__'

    def dispatch(self, request, *args, **kwargs):
        if 'device' in request.session:
            logger.info('Session was already found.')
            return HttpResponseRedirect(reverse('home'))
        logger.info('Session was not found.')
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        logger.info('Form was valid.')
        response = super().form_valid(form)
        self.request.session['device'] = utils.encode_token(self.object.pk)
        self.request.session['device_name'] = self.object.name
        return response

companion/views.py
from django.shortcuts import render

# Create your views here.

clippy/templates/clippy/clip_list.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <title>Pricing example · Bootstrap</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

    </style>

    <!--<link href="pricing.css" rel="stylesheet">-->
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
    <h5 class="my-0 mr-md-auto font-weight-normal">{{ device_name }}</h5>
    <nav class="my-2 my-md-0 mr-md-3">
        <form>
            <input class="form-control" autofocus autocomplete="off" type="text" name="search" placeholder="Search" value="{{ search_value }}">
        </form>
    </nav>
    <a class="btn btn-outline-primary" href="#">Sign up</a>
</div>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Clippy</h1>
</div>

<div class="container">

    <div class="row">
        <div class="col-md-12">
            <textarea class="form-control clipboard-results" readonly="readonly" disabled="disabled">{{ most_recent }}</textarea>
            <br>
            <button class="form-control read-btn">Inspect Clipboard</button>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <ul id="clipboard" class="list-group">
                {% for object in object_list %}
                <li class="list-group-item d-flex justify-content-between lh-condensed">
                    <div class="col-md-10">
                        <code>{{ object.value }}</code>
                        <br>
                        <input type="hidden" id="clipboard-{{ object.pk }}" class="to-copy" value="{{ object.value }}" readonly="readonly">
                        <small class="text-muted">Found in Clipboard: <span id="found-{{ object.pk }}">{{ object.found_in_clipboard }}</span>
                        </small>
                        <br>
                        <small class="text-muted">Saved to Clipboard: <span id="saved-{{ object.pk }}">{{ object.saved_to_clipboard }}</span>
                        </small>
                    </div>
                    <div class="col-md-2">
                        <button name="clipboard-{{ object.pk }}" class="btn btn-outline-primary write-button">Copy to clipboard</button>
                    </div>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.3.1.min.js"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>

<script>
    const readBtn = document.querySelector('.read-btn'); // Paste from Clipboard
    const writeButton = document.querySelector('.write-button'); // Write to Clipboard

    const resultsEl = document.querySelector('.clipboard-results'); // Paste from Clipboard
    url = "http://localhost:8000/api/clips/";
    dataType = "json";

    function saveClipboard() {
        navigator.clipboard.readText()
        .then(text => {
          if (text && text != resultsEl.value) {
              console.log(text + ' vs ' + resultsEl.value)
              resultsEl.value = text;
              data = {
                "value": text,
                "device": "{{ device }}",
                "action": "r"
              }

              $.ajax({
                  type: "POST",
                  url: url,
                  data: data,
                  <!--success: success,-->
                  dataType: dataType
               });
           }
        })
        .catch(err => {
          // console.log('Something went wrong', err);
        })
        setTimeout(saveClipboard, 2000);
    }

    setTimeout(saveClipboard, 2000);

    // Paste from Clipboard
    <!--readBtn.addEventListener('click', () => {-->
      <!--saveClipboard();-->
    <!--});-->

    $( ".write-button" ).click(function() {
      inputValue = $( "#" + this.name )[0].value;
      console.log(inputValue);
      if (inputValue && inputValue != resultsEl.value) {
          navigator.clipboard.writeText(inputValue)
              .then(() => {
                if (this.innerText !== 'Copied!') {
                  const originalText = this.innerText;
                  this.innerText = 'Copied!';
                  setTimeout(() => {
                    this.innerText = originalText;
                  }, 750);

                  data = {
                    "value": inputValue,
                    "device": "{{ device }}",
                    "action": "w"
                  }

                  $.ajax({
                      type: "POST",
                      url: url,
                      data: data,
                      <!--success: success,-->
                      dataType: dataType
                   });

                   resultsEl.value = inputValue;
                }
              })
              .catch(err => {
                console.log('Something went wrong', err);
              });
          }
    });



</script>

</body>
</html>

clippy/templates/clippy/device_form.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <title>Signin Template · Bootstrap</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.3/examples/sign-in/">

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

    </style>
    <!-- Custom styles for this template -->
    <link href="/static/clippy/form.css" rel="stylesheet">
</head>
<body class="text-center">
<form class="form-signin" method="post">
    <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>
    <label for="id_name" class="sr-only">Computer Name</label>
    {% csrf_token %}
    <input type="text" class="form-control" placeholder="Computer Name"  name="name" maxlength="64" id="id_name" required autofocus autocomplete="off">
    <button class="btn btn-lg btn-primary btn-block" type="submit">Submit</button>
    <p class="mt-5 mb-3 text-muted">&copy; 2017-2019</p>
</form>
</body>
</html>

clippy/templates/clippy/home.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <title>Pricing example · Bootstrap</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }


    </style>

    <!--<link href="pricing.css" rel="stylesheet">-->
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
    <h5 class="my-0 mr-md-auto font-weight-normal">{{ device_name }}</h5>
    <nav class="my-2 my-md-0 mr-md-3">
        <a class="p-2 text-dark" href="#">Features</a>
        <a class="p-2 text-dark" href="#">Enterprise</a>
        <a class="p-2 text-dark" href="#">Support</a>
        <a class="p-2 text-dark" href="#">Pricing</a>
    </nav>
    <a class="btn btn-outline-primary" href="#">Sign up</a>
</div>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Pricing</h1>
    <p class="lead">Quickly build an effective pricing table for your potential customers with this Bootstrap example.
        It’s built with default Bootstrap components and utilities with little customization.</p>
</div>

<div class="container">

    <div class="row">
        <input type="text" class="to-copy" placeholder="Type something..." aria-label="Type something">
        <button class="write-btn">Copy to clipboard</button>
    </div>

    <div class="row">
        <h3 class="clipboard-results"></h3>
        <button class="read-btn">Paste from clipboard</button>
    </div>

    <div class="row">

        <div class="col-md-4 order-md-2 mb-4">
            <ul class="list-group mb-3">
                <li class="list-group-item d-flex justify-content-between lh-condensed">
                    <div>
                        <h6 class="my-0">{{ object.value }}</h6>
                        <small class="text-muted">Brief description</small>
                    </div>
                    <span class="text-muted">$12</span>
                </li>
                <li class="list-group-item d-flex justify-content-between lh-condensed">
                    <div>
                        <h6 class="my-0">Second product</h6>
                        <small class="text-muted">Brief description</small>
                    </div>
                    <span class="text-muted">$8</span>
                </li>
                <li class="list-group-item d-flex justify-content-between lh-condensed">
                    <div>
                        <h6 class="my-0">Third item</h6>
                        <small class="text-muted">Brief description</small>
                    </div>
                    <span class="text-muted">$5</span>
                </li>
                <li class="list-group-item d-flex justify-content-between bg-light">
                    <div class="text-success">
                        <h6 class="my-0">Promo code</h6>
                        <small>EXAMPLECODE</small>
                    </div>
                    <span class="text-success">-$5</span>
                </li>
                <li class="list-group-item d-flex justify-content-between">
                    <span>Total (USD)</span>
                    <strong>$20</strong>
                </li>
            </ul>
        </div>
    </div>

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                <small class="d-block mb-3 text-muted">&copy; 2017-2019</small>
            </div>
            <div class="col-6 col-md">
                <h5>Features</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Cool stuff</a></li>
                    <li><a class="text-muted" href="#">Random feature</a></li>
                    <li><a class="text-muted" href="#">Team feature</a></li>
                    <li><a class="text-muted" href="#">Stuff for developers</a></li>
                    <li><a class="text-muted" href="#">Another one</a></li>
                    <li><a class="text-muted" href="#">Last time</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Resources</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Resource</a></li>
                    <li><a class="text-muted" href="#">Resource name</a></li>
                    <li><a class="text-muted" href="#">Another resource</a></li>
                    <li><a class="text-muted" href="#">Final resource</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>About</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Team</a></li>
                    <li><a class="text-muted" href="#">Locations</a></li>
                    <li><a class="text-muted" href="#">Privacy</a></li>
                    <li><a class="text-muted" href="#">Terms</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

<script src="https://code.jquery.com/jquery-3.3.1.min.js"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>

<script>
    const readBtn = document.querySelector('.read-btn');
    const writeBtn = document.querySelector('.write-btn');

    const resultsEl = document.querySelector('.clipboard-results');
    const inputEl = document.querySelector('.to-copy');

    readBtn.addEventListener('click', () => {
      navigator.clipboard.readText()
        .then(text => {
          data = {
            "value": text,
            "device": {{ device }}
          }
          url = "http://localhost:8000/api/clips/";
          dataType = "json";
          $.ajax({
              type: "POST",
              url: url,
              data: data,
              <!--success: success,-->
              dataType: dataType
           });
          resultsEl.innerText = text;
        })
        .catch(err => {
          console.log('Something went wrong', err);
        })
    });

    writeBtn.addEventListener('click', () => {
      const inputValue = inputEl.value.trim();
      if (inputValue) {
        navigator.clipboard.writeText(inputValue)
          .then(() => {
            inputEl.value = '';
            if (writeBtn.innerText !== 'Copied!') {
              const originalText = writeBtn.innerText;
              writeBtn.innerText = 'Copied!';
              setTimeout(() => {
                writeBtn.innerText = originalText;
              }, 1500);
            }
          })
          .catch(err => {
            console.log('Something went wrong', err);
          })
      }
    });

</script>

</body>
</html>